# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r: bioc-devel
#r: bioc-release

bioc_packages:
 - BiocStyle
# - BiocCheck

r_github_packages:
 - r-lib/covr

script:
 - R CMD build .
 - R CMD check --no-build-vignettes *.tar.gz
# - R CMD BiocCheck --no-check-version-num --no-check-deprecated *.tar.gz

#env:
# - PKG_TARBALL=metaseqR2_1.1.15.tar.gz
